[package]
name = "redis-loader"
version = "0.1.0"
authors = ["Keith Zhang <keithohno@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
redis = "0.16.0"
rand = "0.7"
