[package]
name = "compress"
version = "0.1.0"
authors = ["Keith Zhang <keithohno@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
zstd = "0.5"
lz4 = "1.23.1"

[lib]
name = "lib"
path = "src/lib.rs"