[package]
name = "count_zeros"
version = "0.1.0"
authors = ["Keith Zhang <keithohno@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
